# Generated by Django 3.1.7 on 2021-04-09 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('characterid', models.IntegerField(db_column='characterId', primary_key=True, serialize=False)),
                ('charactername', models.CharField(db_column='characterName', max_length=50)),
            ],
            options={
                'db_table': 'character',
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('crewid', models.CharField(db_column='crewId', max_length=50, primary_key=True, serialize=False)),
                ('primaryname', models.CharField(db_column='primaryName', max_length=50)),
                ('birthyear', models.IntegerField(blank=True, db_column='birthYear', null=True)),
                ('deathyear', models.IntegerField(blank=True, db_column='deathYear', null=True)),
            ],
            options={
                'db_table': 'crew',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('languageid', models.AutoField(db_column='languageId', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('primarytitle', models.CharField(blank=True, db_column='primaryTitle', max_length=100, null=True)),
                ('originaltitle', models.CharField(blank=True, db_column='originalTitle', max_length=100, null=True)),
                ('runtimeminutes', models.IntegerField(blank=True, db_column='runtimeMinutes', null=True)),
                ('isadult', models.IntegerField(blank=True, db_column='isAdult', null=True)),
                ('releaseyear', models.IntegerField(blank=True, db_column='releaseYear', null=True)),
                ('averagerating', models.IntegerField(blank=True, db_column='averageRating', null=True)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('professionid', models.IntegerField(db_column='professionId', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'profession',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleid', models.IntegerField(db_column='roleId', primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.IntegerField(db_column='userId', primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, db_column='firstName', max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, db_column='lastName', max_length=50, null=True)),
                ('emailaddress', models.CharField(blank=True, db_column='emailAddress', max_length=50, null=True)),
                ('upassword', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('userid', models.OneToOneField(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='movie.user')),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'password',
            },
        ),
        migrations.CreateModel(
            name='MovieRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.movie')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.region')),
            ],
            options={
                'db_table': 'movie_region',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='movie.movie')),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('userid', models.ForeignKey(blank=True, db_column='userId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='movie.user')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('roleid', models.OneToOneField(db_column='roleId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='movie.role')),
                ('userid', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.DO_NOTHING, to='movie.user')),
            ],
            options={
                'db_table': 'user_role',
                'unique_together': {('roleid', 'userid')},
            },
        ),
        migrations.CreateModel(
            name='MovieLanguage',
            fields=[
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='movie.movie')),
                ('languageid', models.ForeignKey(db_column='languageId', on_delete=django.db.models.deletion.DO_NOTHING, to='movie.language')),
            ],
            options={
                'db_table': 'movie_language',
                'unique_together': {('movie', 'languageid')},
            },
        ),
        migrations.CreateModel(
            name='MovieCrew',
            fields=[
                ('movieid', models.OneToOneField(db_column='movieId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='movie.movie')),
                ('crewid', models.ForeignKey(db_column='crewId', on_delete=django.db.models.deletion.DO_NOTHING, to='movie.crew')),
            ],
            options={
                'db_table': 'movie_crew',
                'unique_together': {('movieid', 'crewid')},
            },
        ),
        migrations.CreateModel(
            name='MovieCategory',
            fields=[
                ('movie', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='movie.movie')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='movie.category')),
            ],
            options={
                'db_table': 'movie_category',
                'unique_together': {('movie', 'category')},
            },
        ),
        migrations.CreateModel(
            name='CrewProfession',
            fields=[
                ('crewid', models.OneToOneField(db_column='crewId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='movie.crew')),
                ('professionid', models.ForeignKey(db_column='professionId', on_delete=django.db.models.deletion.DO_NOTHING, to='movie.profession')),
            ],
            options={
                'db_table': 'crew_profession',
                'unique_together': {('crewid', 'professionid')},
            },
        ),
        migrations.CreateModel(
            name='CrewCharacter',
            fields=[
                ('crewid', models.OneToOneField(db_column='crewId', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='movie.crew')),
                ('characterid', models.ForeignKey(db_column='characterId', on_delete=django.db.models.deletion.DO_NOTHING, to='movie.character')),
            ],
            options={
                'db_table': 'crew_character',
                'unique_together': {('crewid', 'characterid')},
            },
        ),
    ]
