# Generated by Django 3.1.7 on 2021-04-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('movie_id', models.AutoField(primary_key=True, serialize=False)),
                ('primarytitle', models.CharField(max_length=100)),
                ('originaltitle', models.CharField(max_length=100)),
                ('averagerating', models.IntegerField()),
            ],
        ),
    ]
